spring:
  datasource:
    url: jdbc:mysql://localhost:3306/omin_link?useSSL=false
    username: omin_link
    password: ${DATABASE_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update

# App Properties
ominlink:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
