spring:
  datasource:
    url: jdbc:mysql://localhost:3306/omin_link?useSSL=false
    username: omin_link
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update

# App Properties
ominlink:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000
